name: "labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  relabel:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # scope
      - name: label-scope-by-changed-files
        if: ${{ github.event_name == 'pull_request_target' && github.event.action != 'edited' }}
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
      # sem-pr-type
      - name: sem-pr-info
        if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'opened' || github.event.action == 'edited') }}
        id: info
        uses: hankei6km/gha-sem-from-title@v0
        with:
          title: ${{ github.event.pull_request.title }}
      - name: relabel-by-sem-pr-type
        if: ${{ github.event_name == 'pull_request_target' && (github.event.action == 'opened' || github.event.action == 'edited') }}
        uses: hankei6km/gha-sem-pr-labeler@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          pr_num: ${{ github.event.pull_request.number }}
          type: ${{ steps.info.outputs.type }}
          is_breaking_change: ${{ steps.info.outputs.is_breaking_change }}
